### ISSUE TITLE
Docker to install openSIS

### ISSUE THREAD

**Issue by VfanLee** [OS4ED/openSIS-Classic#293]
Here is the directory structure

```
├── docker-compose.yml
├── Dockerfile
├── mysql
├── opensis  # unzip opensis project
└── openSIS9.0.zip  # origin opensis project
```

**Dockerfile**

```Dockerfile
FROM php:8.2-apache

RUN docker-php-ext-install pdo_mysql mysqli
# 'opensis' is project path
COPY opensis /var/www/html

RUN chmod -R 777 /var/www/html
```

**docker-compose.yml**

```yml
version: "3"

services:
  web:
    build: .
    ports:
      - "80:80"
    networks:
      - opensis-network
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: opensis # 'opensis' is mysql password
    networks:
      - opensis-network
    command: --sql_mode=""

networks:
  opensis-network:
```
